name: Deploy Storybook to Chromatic

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install
          yarn global add chromatic-cli

      - name: Build Storybook
        run: yarn build-storybook

      - name: UI Testing and Storybook Publishing
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # CHROMATIC_USERNAME: ${{ secrets.CHROMATIC_USERNAME }}
          # CHROMATIC_PASSWORD: ${{ secrets.CHROMATIC_PASSWORD }}
        run: |
          yarn test-ui
          npx chromatic --exit-zero-on-changes
