name: Chromatic Workflow

on:
  pull_request:
    branches: [main]

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install
          yarn global add chromatic-cli

      - name: Build and Test
        run: |
          yarn

      - name: Publish Storybook to Chromatic
        if: github.ref == 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: 46d49e475ab7
          # Location of Storybook build output
          storybookBuildDir: ./storybook-static

      - name: Chromatic UI Tests
        if: github.ref == 'refs/heads/main'
        run: |
          npx chromatic --project-token=46d49e475ab7
