name: Chromatic Workflow

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          yarn install
          yarn global add chromatic-cli

      - name: Publish Storybook to Chromatic
        # if: github.ref == 'refs/heads/main'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: cf7d99e69e32
          # Location of Storybook build output
          # storybookBuildDir: storybook-static

      - name: Chromatic UI Tests
        # if: github.ref == 'refs/heads/main'
        run: |
          npx chromatic --project-token=cf7d99e69e32
