name: Deploy Storybook to Chromatic

on:
  push:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Deploy to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.CHROMATIC_TOKEN }}
          projectToken: cf7d99e69e32
          storybookBuildDir: storybook-static
