# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on: pull_request

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    node-version: [16.x]
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        run: npx chromatic --project-token=cf7d99e69e32
        # # Chromatic GitHub Action options
        # with:
        #   # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        #   projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
