# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on: pull_request

# defaults:
#   run:
#     working-directory: frontend

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        # uses: chromaui/action@v1
        # # Chromatic GitHub Action options
        # with:
        #   # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        #   projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        #   workingDir: .

        uses: chromaui/action@v1
        with:
          token: ${{ secrets.TT }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: stories
